modLoader="javafml"
loaderVersion="[43,)"
license="Academic Free License v3.0"

[[mods]]
modId="ths"
version="0.0.4-prerelease"
displayName="Thigh High Socks"
credits="Angel Martin, and partialy MCreator"
displayURL="https://mcreator.net"
authors="Angel, MCreator"
description="A Mod for Minecraft that adds Thigh High Socks"

[[dependencies.ths]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.2]"
    ordering="NONE"
    side="BOTH"




