modLoader="javafml"
loaderVersion="[43,)"
license="Academic Free License v3.0"

[[mods]]
modId="ths"
version="0.1.0"
displayName="Thigh High Socks"
credits="Thanks to SquidDogTheLatexBoi#7345 for helping with the textures"
displayURL="https://mcreator.net"
authors="AM7999#8935, SquidDogTheLatexBoi#7345"
description="A Mod for Minecraft that adds Thigh High Socks"

[[dependencies.ths]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.2]"
    ordering="NONE"
    side="BOTH"




