name: Compiling

on:
  push:
  pull_request:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Compile
      uses: Ruochenfu2011/compilation@v1
      
    - name: Archive Thigh-High-Socks_1.19.2-Forge
      uses: actions/upload-artifact@v2
      with:
        name: Thigh-High-Socks_1.19.2-Forge
        path: ./build/libs
